name: Sync Build Release

on:
  schedule:
    - cron: '0 6 * * *'  # Daily at 6 AM UTC
  workflow_dispatch: { }

jobs:
  sync:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    outputs:
      has-changes: ${{ steps.sync.outputs.has-changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get current commit
        id: before
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Sync fork
        run: gh repo sync $REPOSITORY -b $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Check for changes
        id: sync
        run: |
          git fetch origin
          CURRENT_SHA=$(git rev-parse HEAD)
          NEW_SHA=$(git rev-parse origin/${{ github.ref_name }})
          if [ "$CURRENT_SHA" != "$NEW_SHA" ] || [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "has-changes=true" >> $GITHUB_OUTPUT
          else
            echo "has-changes=false" >> $GITHUB_OUTPUT
          fi

  build:
    needs: sync
    if: needs.sync.outputs.has-changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {os: linux, arch: amd64, goos: linux, goarch: amd64}
          - {os: linux, arch: arm64, goos: linux, goarch: arm64}
          - {os: darwin, arch: amd64, goos: darwin, goarch: amd64}
          - {os: darwin, arch: arm64, goos: darwin, goarch: arm64}
          - {os: windows, arch: amd64, goos: windows, goarch: amd64, ext: .exe}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          cd cmd/github-mcp-server
          OUTPUT_NAME="github-mcp-server-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}"
          go build -ldflags="-s -w" -o "../../$OUTPUT_NAME" .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-mcp-server-${{ matrix.os }}-${{ matrix.arch }}
          path: github-mcp-server-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }}

  release:
    needs: [sync, build]
    if: needs.sync.outputs.has-changes == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Get commit info
        id: commit
        run: |
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: unofficial-${{ steps.commit.outputs.sha }}
          name: GitHub MCP Server Unofficial ${{ steps.commit.outputs.date }}
          body: |
            Automated build from synced upstream repository.
            
            ## Usage
            ```bash
            # Download and make executable
            chmod +x github-mcp-server-linux-amd64
            
            # Set your GitHub token
            export GITHUB_PERSONAL_ACCESS_TOKEN=your_token
            
            # Run the server
            ./github-mcp-server-linux-amd64
            ```
          files: |
            github-mcp-server-*/github-mcp-server-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
